### ISSUE TITLE
Switch Workspace when moving the last window in a workspace to another monitor

### ISSUE THREAD

**Issue by pgmorgan** [giuseppe-dandrea/i3-switch-if-workspace-empty#1]
When you are working with more than one monitor, and you move the last or only window in a given workspace to another monitor (also moving the focus to the window in the new workspace/monitor), then the previous workspace remains empty and does not switch to the next non-empty workspace on that monitor.

Can this be resolved?

**Comment by giuseppe-dandrea** [comment]
Have you tried using `--keep-same-output` param?
